version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    hostname: mysql-container
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/initdb.d
  backend:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ../:/workspaces
      # - $HOME/.aws:/home/vscode/.aws
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      APP_ENV: local
      APP_DB_DNS: todo_app:password@tcp(db)/todo_app
      # APP_DB_DNS: todo_app:password@tcp(localhost:3307)/todo_app
      # APP_DB_DNS: todo_app:password@(host.docker.internal:3307)/todo_app

volumes:
  db-todo: